```{r}
library(tidyverse)
library(rstan)
source("utils/plotting.r")
```

## Data

```{r}
df <- readRDS("data-clean/combined-data-wr.rds")
```

## Modeling

### Prep data

```{r}
stan_dat <- list()

df_daily <- df %>%
  group_by(year, date) %>%
  summarise(
    temp = mean(temperature, na.rm = TRUE),
    rH = mean(humidity, na.rm = TRUE),
    co2 = mean(co2, na.rm = TRUE),
    np = mean(np, na.rm = TRUE),
    diagnosed = sum(diagnosed),
    registered = sum(registered),
    sampling_time = sum(sampling_time)
  ) %>%
  ungroup() %>%
  group_by(year) %>%
  mutate(day = as.integer(factor(date))) %>%
  ungroup()

df_daily_par <- df_daily %>%
  summarise(
    across(c(temp, rH, co2, np), list(mean = mean, sd = sd),
      na.rm = TRUE, .names = "{.col}_{.fn}"
    )
  ) %>%
  ungroup()

df_daytime <- df %>%
  dplyr::select(year, date, daytime, dna_copies, sampling_time, pt) %>%
  mutate(daytime = factor(daytime, levels = c("Morning", "Afternoon"))) %>%
  arrange(year, date, daytime) %>%
  group_by(year) %>%
  mutate(day = as.integer(factor(date))) %>%
  ungroup()

df_daytime_par <- df_daytime %>%
  group_by(daytime) %>%
  summarise(
    across(c(dna_copies, pt), list(mean = mean, sd = sd),
      na.rm = TRUE, .names = "{.col}_{.fn}"
    )
  ) %>%
  ungroup()

# meta
stan_dat$N <- nrow(df_daily)
stan_dat$year <- ifelse(df_daily$year == 2019, 0, 1)
stan_dat$N_dt <- nrow(df_daytime)
stan_dat$year_dt <- ifelse(df_daytime$year == 2019, 0, 1)
stan_dat$D1 <- unique(df_daily$day[df_daytime$year == 2019])
stan_dat$D2 <- unique(df_daily$day[df_daytime$year == 2021])
stan_dat$D1_dt <- unique(df_daytime$day[df_daytime$year == 2019])
stan_dat$D2_dt <- unique(df_daytime$day[df_daytime$year == 2021])
stan_dat$dt <- as.integer(df_daytime$daytime) - 1

# molecular data
stan_dat$y_dt <- ifelse(is.na(df_daytime$dna_copies), -1, df_daytime$dna_copies)
stan_dat$is_mis_y_dt <- ifelse(is.na(df_daytime$dna_copies), 1, 0)
stan_dat$mis_y_dt <- (as.integer(df_daytime$daytime) - 1)[is.na(df_daytime$dna_copies)]
stan_dat$n_mis_y_dt <- sum(stan_dat$is_mis_y)
stan_dat$st <- df_daily$sampling_time
stan_dat$mu_y_dt <- df_daytime_par$dna_copies_mean
stan_dat$sigma_y_dt <- df_daytime_par$dna_copies_sd

# tracking data
stan_dat$pt_dt <- ifelse(is.na(df_daytime$pt), -1, df_daytime$pt)
stan_dat$is_mis_pt_dt <- ifelse(is.na(df_daytime$pt), 1, 0)
stan_dat$mis_pt_dt <- (as.integer(df_daytime$daytime) - 1)[is.na(df_daytime$pt)]
stan_dat$n_mis_pt_dt <- sum(stan_dat$is_mis_pt)
stan_dat$mu_pt_dt <- df_daytime_par$pt_mean
stan_dat$sigma_pt_dt <- df_daytime_par$pt_sd

# environmental data
stan_dat$temp <- ifelse(is.na(df_daily$temp), -1, df_daily$temp)
stan_dat$rH <- ifelse(is.na(df_daily$rH), -1, df_daily$rH)
stan_dat$co2 <- ifelse(is.na(df_daily$co2), -1, df_daily$co2)
stan_dat$np <- ifelse(is.na(df_daily$np), -1, df_daily$np)
stan_dat$is_mis_temp <- ifelse(is.na(df_daily$temp), 1, 0)
stan_dat$is_mis_rH <- ifelse(is.na(df_daily$rH), 1, 0)
stan_dat$is_mis_co2 <- ifelse(is.na(df_daily$co2), 1, 0)
stan_dat$is_mis_np <- ifelse(is.na(df_daily$np), 1, 0)
stan_dat$n_mis_temp <- sum(stan_dat$is_mis_temp)
stan_dat$n_mis_rH <- sum(stan_dat$is_mis_rH)
stan_dat$n_mis_co2 <- sum(stan_dat$is_mis_co2)
stan_dat$n_mis_np <- sum(stan_dat$is_mis_np)
stan_dat$mu_temp <- df_daily_par$temp_mean
stan_dat$sigma_temp <- df_daily_par$temp_sd
stan_dat$mu_rH <- df_daily_par$rH_mean
stan_dat$sigma_rH <- df_daily_par$rH_sd
stan_dat$mu_co2 <- df_daily_par$co2_mean
stan_dat$sigma_co2 <- df_daily_par$co2_sd
stan_dat$mu_np <- df_daily_par$np_mean
stan_dat$sigma_np <- df_daily_par$np_sd

# clinical data
stan_dat$registered <- df_daily$registered
stan_dat$p_diag <- df_daily$diagnosed / df_daily$registered
stam_dat$alpha_p_undiag <- mean(stan_dat$p_diag) *
  ((mean(stan_dat$p_diag) * (1 - mean(stan_dat$p_diag)) /
    var(stan_dat$p_diag)) - 1)
stan_dat$beta_p_undiag <- (1 - mean(stan_dat$p_diag)) *
  ((mean(stan_dat$p_diag) * (1 - mean(stan_dat$p_diag)) /
    var(stan_dat$p_diag)) - 1)
```