```{r}
library(tidyverse)
source("utils/plotting.r")
source("utils/trans_risk.r")
source("utils/tex.r")
```

## Data

```{r}
df <- readRDS("data-clean/combined-data-wr.rds") %>%
  mutate(year = factor(year, levels = c(2019, 2021)))
```

## Descriptives

```{r}
custom_boxplot <- function(dat) {
  p_value <- ggpubr::compare_means(
    y ~ year,
    data = dat, method = "t.test"
  )$p.adj
  p_value <- ifelse(
    p_value < .001, "p < .001",
    paste("p =", round(p_value, 3))
  )
  dat %>%
    ggplot(aes(
      x = year,
      y = y
    )) +
    geom_boxplot(aes(fill = year)) +
    geom_jitter(width = .1, height = 0, alpha = .5) +
    ggsignif::geom_signif(
      comparisons = list(c("2019", "2021")),
      map_signif_level = FALSE,
      textsize = 8 / cm(1),
      annotations = p_value,
    ) +
    scale_fill_manual(
      values = wes_palette("Zissou1")[c(2, 4)]
    ) +
    scale_y_continuous(
      expand = expansion(mult = c(.01, .1))
    ) +
    theme_custom() +
    theme(
      axis.title.x = element_blank(),
      legend.position = "none"
    )
}
```

### Molecular

```{r}
mol_pl <- df %>%
  filter(!is.na(dna_copies)) %>%
  group_by(year, date) %>%
  summarise(
    dna_copies = sum(dna_copies, na.rm = TRUE),
    sampling_time = sum(sampling_time, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  mutate(
    y = log1p(dna_copies / sampling_time)
  ) %>%
  custom_boxplot() +
  labs(
    y = expression("Log DNA copies per " * mu * "L hour of sampling"),
    title = "a | Bacterial concentration in bioaerosols",
  )

mol_pl
```

### Environmental

```{r}
aer_pl <- df %>%
  filter(!is.na(aer)) %>%
  group_by(year, date) %>%
  summarise(
    y = mean(aer, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  custom_boxplot() +
  labs(
    y = "Air changes per hour",
    title = "b | Air exchange rate",
  )

aer_pl

df %>%
  group_by(year) %>%
  summarise(
    mean_aer = mean(aer, na.rm = TRUE),
    q25 = quantile(aer, .25, na.rm = TRUE),
    q75 = quantile(aer, .75, na.rm = TRUE)
  )

rH_pl <- df %>%
  filter(!is.na(humidity)) %>%
  group_by(year, date) %>%
  summarise(
    y = mean(humidity, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  custom_boxplot() +
  labs(
    y = "Relative humidity (%)",
    title = "c | Relative humidity",
  )

rH_pl

df %>%
  group_by(year) %>%
  summarise(
    mean_rh = mean(humidity, na.rm = TRUE),
    q25 = quantile(humidity, .25, na.rm = TRUE),
    q75 = quantile(humidity, .75, na.rm = TRUE)
  )
```

```{r}
df %>%
  dplyr::select(year, date, daytime, aer) %>%
  pivot_wider(
    names_from = daytime,
    values_from = aer
  ) %>%
  dplyr::select(Morning, Afternoon) %>%
  ggpairs()
```

### Tracking

```{r}
track_pl <- df %>%
  dplyr::select(year, date, matches("pt_hr")) %>%
  pivot_longer(
    cols = -c(year, date),
    names_to = "daytime",
    values_to = "pt"
  ) %>%
  mutate(
    daytime = gsub("pt_hr", "", daytime),
    daytime = as.numeric(daytime),
    daytime = ifelse(daytime <= 11, "Morning", "Afternoon"),
    daytime = factor(daytime, levels = c("Morning", "Afternoon"))
  ) %>%
  group_by(year, date) %>%
  filter(all(!is.na(pt))) %>%
  summarise(
    pt = sum(pt)
  ) %>%
  ungroup() %>%
  mutate(
    y = pt
  ) %>%
  custom_boxplot() +
  labs(
    y = "Person-time (hours)",
    title = "d | Person-time in clinic",
  )

track_pl
```

### Clinical

```{r}
reg_pl <- df %>%
  filter(!is.na(registered)) %>%
  group_by(year, date) %>%
  summarise(
    y = sum(registered, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  custom_boxplot() +
  labs(
    y = "Number of registered patients",
    title = "e | Registered patients",
  )

reg_pl

diagn_pl <- df %>%
  filter(!is.na(diagnosed)) %>%
  group_by(year, date) %>%
  summarise(
    y = sum(diagnosed, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  custom_boxplot() +
  labs(
    y = "Number of diagnosed TB patients",
    title = "f | Diagnosed TB patients",
  )

diagn_pl

df %>%
  ggplot(aes(
    x = factor(year),
    y = diagnosed / registered,
  )) +
  geom_boxplot() +
  facet_wrap(~daytime) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme_custom()

df %>%
  mutate(
    pt = ifelse(daytime == "Morning",
      pt_hr8 + pt_hr9 + pt_hr10 + pt_hr11,
      pt_hr12 + pt_hr13 + pt_hr14 + pt_hr15
    ),
    ipt = diagnosed / registered * pt
  ) %>%
  dplyr::select(year, date, daytime, ipt) %>%
  ggplot(aes(
    x = factor(year),
    y = ipt
  )) +
  geom_boxplot() +
  facet_wrap(~daytime) +
  theme_custom()
```

```{r}
df %>%
  mutate(
    pt = ifelse(daytime == "Morning",
      pt_hr8 + pt_hr9 + pt_hr10 + pt_hr11,
      pt_hr12 + pt_hr13 + pt_hr14 + pt_hr15
    ),
    ipt = diagnosed / registered * pt
  ) %>%
  dplyr::select(date, daytime, ipt) %>%
  pivot_wider(
    names_from = daytime,
    values_from = ipt
  ) %>%
  dplyr::select(Morning, Afternoon) %>%
  ggpairs()
```

### Summary
```{r}
descriptive_pl <- cowplot::plot_grid(
  mol_pl, aer_pl, rH_pl, track_pl, reg_pl, diagn_pl,
  nrow = 3, align = "v"
)

save_plot(
  descriptive_pl,
  "results/descriptives.png",
  w = 16,
  h = 20
)
```

```{r}

```